### ISSUE TITLE
Large Repo Size

### ISSUE THREAD

**Issue by taigrr** [MrEliptik/SudokuResolver#14]
This repos is too big for what it contains. It looks like there was a .rar file in there and you deleted it in a commit.

Can you please take a look at [this](https://help.github.com/articles/removing-sensitive-data-from-a-repository/) link and use it to remove the file from all the history as well? That way there aren't gobs of data required for cloning the repo that will never be used.

I can do it on my fork, and I would have, except you appear to be GPG signing every commit, and if I rewrite them the signatures will fail.

**Comment by MrEliptik** [comment]
I've used BFG repo cleaner to clean samples.rar. It seems to have worked correctly, can you confirm?
I'm not aware of the GPG signature, what is that?

**Comment by taigrr** [comment]
As far as GPG goes,  it seems it was a UI update to Github. Github used to only show the verified badge on GPG signed commits but now it shows verified on merges that you've approved within GH too (Github signs the commit for you).

As far as the BFG repo cleaner, it's possible it didn't work, or you need to run the command to clean the cached files because the repo size is still 60mb.

![image](https://user-images.githubusercontent.com/8261498/49724685-bb83de00-fc1e-11e8-8031-37fff6b10517.png)

**Comment by taigrr** [comment]
I ac
